set_property PACKAGE_PIN AB11 [get_ports CLK]
set_property PACKAGE_PIN AA13 [get_ports RSTB]
set_property PACKAGE_PIN W13 [get_ports {LED[0]}]
set_property PACKAGE_PIN Y12 [get_ports {LED[1]}]
set_property PACKAGE_PIN AA12 [get_ports {LED[2]}]
set_property PACKAGE_PIN AB13 [get_ports {LED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports RSTB]


create_clock -period 40.000 -name clk -waveform {0.000 20.000} [get_ports CLK]