
set_property PACKAGE_PIN F23 [get_ports {ddr\.sys_clk_p} ]
set_property PACKAGE_PIN F24 [get_ports {ddr\.sys_clk_n} ]

set_property PACKAGE_PIN B27 [get_ports {ddr\.dqs_t[0]}]
set_property PACKAGE_PIN A27 [get_ports {ddr\.dqs_c[0]}]
set_property PACKAGE_PIN E30 [get_ports {ddr\.dqs_t[1]}]
set_property PACKAGE_PIN D30 [get_ports {ddr\.dqs_c[1]}]
set_property PACKAGE_PIN G31 [get_ports {ddr\.dqs_t[2]}]
set_property PACKAGE_PIN F31 [get_ports {ddr\.dqs_c[2]}]
set_property PACKAGE_PIN J25 [get_ports {ddr\.dqs_t[3]}]
set_property PACKAGE_PIN H25 [get_ports {ddr\.dqs_c[3]}]
set_property PACKAGE_PIN B16 [get_ports {ddr\.dqs_t[4]}]
set_property PACKAGE_PIN B15 [get_ports {ddr\.dqs_c[4]}]
set_property PACKAGE_PIN E16 [get_ports {ddr\.dqs_t[5]}]
set_property PACKAGE_PIN E15 [get_ports {ddr\.dqs_c[5]}]
set_property PACKAGE_PIN G15 [get_ports {ddr\.dqs_t[6]}]
set_property PACKAGE_PIN F14 [get_ports {ddr\.dqs_c[6]}]
set_property PACKAGE_PIN L17 [get_ports {ddr\.dqs_t[7]}]
set_property PACKAGE_PIN L16 [get_ports {ddr\.dqs_c[7]}]

set_property PACKAGE_PIN C29 [get_ports {ddr\.dm_dbi_n[0]}]
set_property PACKAGE_PIN F28 [get_ports {ddr\.dm_dbi_n[1]}]
set_property PACKAGE_PIN J30 [get_ports {ddr\.dm_dbi_n[2]}]
set_property PACKAGE_PIN M25 [get_ports {ddr\.dm_dbi_n[3]}]
set_property PACKAGE_PIN C18 [get_ports {ddr\.dm_dbi_n[4]}]
set_property PACKAGE_PIN F19 [get_ports {ddr\.dm_dbi_n[5]}]
set_property PACKAGE_PIN J15 [get_ports {ddr\.dm_dbi_n[6]}]
set_property PACKAGE_PIN M16 [get_ports {ddr\.dm_dbi_n[7]}]

set_property PACKAGE_PIN A29 [get_ports {ddr\.dq[0]} ]
set_property PACKAGE_PIN B31 [get_ports {ddr\.dq[1]} ]
set_property PACKAGE_PIN C28 [get_ports {ddr\.dq[2]} ]
set_property PACKAGE_PIN B26 [get_ports {ddr\.dq[3]} ]
set_property PACKAGE_PIN A28 [get_ports {ddr\.dq[4]} ]
set_property PACKAGE_PIN A31 [get_ports {ddr\.dq[5]} ]
set_property PACKAGE_PIN A26 [get_ports {ddr\.dq[6]} ]
set_property PACKAGE_PIN C27 [get_ports {ddr\.dq[7]} ]
set_property PACKAGE_PIN E26 [get_ports {ddr\.dq[8]} ]
set_property PACKAGE_PIN E28 [get_ports {ddr\.dq[9]} ]
set_property PACKAGE_PIN D28 [get_ports {ddr\.dq[10]}]
set_property PACKAGE_PIN E31 [get_ports {ddr\.dq[11]}]
set_property PACKAGE_PIN D26 [get_ports {ddr\.dq[12]}]
set_property PACKAGE_PIN E29 [get_ports {ddr\.dq[13]}]
set_property PACKAGE_PIN D27 [get_ports {ddr\.dq[14]}]
set_property PACKAGE_PIN D31 [get_ports {ddr\.dq[15]}]
set_property PACKAGE_PIN G29 [get_ports {ddr\.dq[16]}]
set_property PACKAGE_PIN G30 [get_ports {ddr\.dq[17]}]
set_property PACKAGE_PIN H29 [get_ports {ddr\.dq[18]}]
set_property PACKAGE_PIN H28 [get_ports {ddr\.dq[19]}]
set_property PACKAGE_PIN H30 [get_ports {ddr\.dq[20]}]
set_property PACKAGE_PIN F27 [get_ports {ddr\.dq[21]}]
set_property PACKAGE_PIN G27 [get_ports {ddr\.dq[22]}]
set_property PACKAGE_PIN J28 [get_ports {ddr\.dq[23]}]
set_property PACKAGE_PIN L27 [get_ports {ddr\.dq[24]}]
set_property PACKAGE_PIN G26 [get_ports {ddr\.dq[25]}]
set_property PACKAGE_PIN H27 [get_ports {ddr\.dq[26]}]
set_property PACKAGE_PIN J26 [get_ports {ddr\.dq[27]}]
set_property PACKAGE_PIN J27 [get_ports {ddr\.dq[28]}]
set_property PACKAGE_PIN L26 [get_ports {ddr\.dq[29]}]
set_property PACKAGE_PIN K26 [get_ports {ddr\.dq[30]}]
set_property PACKAGE_PIN G25 [get_ports {ddr\.dq[31]}]
set_property PACKAGE_PIN C14 [get_ports {ddr\.dq[32]}]
set_property PACKAGE_PIN B17 [get_ports {ddr\.dq[33]}]
set_property PACKAGE_PIN A18 [get_ports {ddr\.dq[34]}]
set_property PACKAGE_PIN A17 [get_ports {ddr\.dq[35]}]
set_property PACKAGE_PIN C15 [get_ports {ddr\.dq[36]}]
set_property PACKAGE_PIN A19 [get_ports {ddr\.dq[37]}]
set_property PACKAGE_PIN A16 [get_ports {ddr\.dq[38]}]
set_property PACKAGE_PIN B19 [get_ports {ddr\.dq[39]}]
set_property PACKAGE_PIN F16 [get_ports {ddr\.dq[40]}]
set_property PACKAGE_PIN D17 [get_ports {ddr\.dq[41]}]
set_property PACKAGE_PIN F17 [get_ports {ddr\.dq[42]}]
set_property PACKAGE_PIN E19 [get_ports {ddr\.dq[43]}]
set_property PACKAGE_PIN D15 [get_ports {ddr\.dq[44]}]
set_property PACKAGE_PIN D18 [get_ports {ddr\.dq[45]}]
set_property PACKAGE_PIN D16 [get_ports {ddr\.dq[46]}]
set_property PACKAGE_PIN E18 [get_ports {ddr\.dq[47]}]
set_property PACKAGE_PIN H18 [get_ports {ddr\.dq[48]}]
set_property PACKAGE_PIN H17 [get_ports {ddr\.dq[49]}]
set_property PACKAGE_PIN G17 [get_ports {ddr\.dq[50]}]
set_property PACKAGE_PIN G14 [get_ports {ddr\.dq[51]}]
set_property PACKAGE_PIN G19 [get_ports {ddr\.dq[52]}]
set_property PACKAGE_PIN H14 [get_ports {ddr\.dq[53]}]
set_property PACKAGE_PIN H19 [get_ports {ddr\.dq[54]}]
set_property PACKAGE_PIN G16 [get_ports {ddr\.dq[55]}]
set_property PACKAGE_PIN L18 [get_ports {ddr\.dq[56]}]
set_property PACKAGE_PIN K15 [get_ports {ddr\.dq[57]}]
set_property PACKAGE_PIN K18 [get_ports {ddr\.dq[58]}]
set_property PACKAGE_PIN J16 [get_ports {ddr\.dq[59]}]
set_property PACKAGE_PIN K19 [get_ports {ddr\.dq[60]}]
set_property PACKAGE_PIN K14 [get_ports {ddr\.dq[61]}]
set_property PACKAGE_PIN L19 [get_ports {ddr\.dq[62]}]
set_property PACKAGE_PIN K16 [get_ports {ddr\.dq[63]}]

set_property PACKAGE_PIN A22 [get_ports {ddr\.adr[0]} ]
set_property PACKAGE_PIN B22 [get_ports {ddr\.adr[1]} ]
set_property PACKAGE_PIN F22 [get_ports {ddr\.adr[2]} ]
set_property PACKAGE_PIN E21 [get_ports {ddr\.adr[3]} ]
set_property PACKAGE_PIN D21 [get_ports {ddr\.adr[4]} ]
set_property PACKAGE_PIN C25 [get_ports {ddr\.adr[5]} ]
set_property PACKAGE_PIN G22 [get_ports {ddr\.adr[6]} ]
set_property PACKAGE_PIN G24 [get_ports {ddr\.adr[7]} ]
set_property PACKAGE_PIN H24 [get_ports {ddr\.adr[8]} ]
set_property PACKAGE_PIN G21 [get_ports {ddr\.adr[9]} ]
set_property PACKAGE_PIN B21 [get_ports {ddr\.adr[10]}]
set_property PACKAGE_PIN B25 [get_ports {ddr\.adr[11]}]
set_property PACKAGE_PIN A21 [get_ports {ddr\.adr[12]}]
set_property PACKAGE_PIN B24 [get_ports {ddr\.adr[13]}]
set_property PACKAGE_PIN C20 [get_ports {ddr\.adr[14]}]
set_property PACKAGE_PIN D20 [get_ports {ddr\.adr[15]}]
set_property PACKAGE_PIN B20 [get_ports {ddr\.adr[16]}]

set_property PACKAGE_PIN D22 [get_ports {ddr\.ck_t[0]}]
set_property PACKAGE_PIN D23 [get_ports {ddr\.ck_c[0]}]
set_property PACKAGE_PIN F21 [get_ports {ddr\.ba[0]}  ]
set_property PACKAGE_PIN J21 [get_ports {ddr\.ba[1]}  ]
set_property PACKAGE_PIN C22 [get_ports {ddr\.bg[0]}  ]
set_property PACKAGE_PIN J20 [get_ports {ddr\.cke[0]} ]
set_property PACKAGE_PIN E20 [get_ports {ddr\.cs_n[0]}]
set_property PACKAGE_PIN G20 [get_ports {ddr\.odt[0]} ]
set_property PACKAGE_PIN H20 [get_ports {ddr\.act_n}  ]
set_property PACKAGE_PIN A24 [get_ports {ddr\.reset_n}]

### IOSTANARD
set_property IOSTANDARD DIFF_SSTL12 [get_ports {ddr\.sys_clk_p}]
set_property IOSTANDARD DIFF_SSTL12 [get_ports {ddr\.sys_clk_n}]
set_property IOSTANDARD LVCMOS12 [get_ports {ddr\.reset_n}]
set_property DRIVE 8 [get_ports {ddr\.reset_n}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr\.act_n}]
set_property IOSTANDARD DIFF_SSTL12_DCI [get_ports {ddr\.ck_c[0]}]
set_property IOSTANDARD DIFF_SSTL12_DCI [get_ports {ddr\.ck_t[0]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr\.ba[*]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr\.bg[0]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr\.adr[*]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr\.cs_n[0]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr\.cke[0]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr\.odt[0]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr\.dq[*]}]
set_property IOSTANDARD POD12_DCI [ get_ports {ddr\.dm_dbi_n[*]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddr\.dqs_c[*]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddr\.dqs_t[*]}]
